# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GzbcIBuLjKJ6fEzBtLaZrvG76v711xHJ
"""

def calculate_volume_of_sphere(radius):
  pi = 3.14
  volume = pi * (4/3) * (radius ** 3)
  return volume

radius1 = 30
volume1 = calculate_volume_of_sphere(radius1)
print(volume1)

radius2 = 40
volume2 = calculate_volume_of_sphere(radius2)
print(volume2)